name: Append Temp Files

on:
  push:
    branches:
      - main
permissions:  
  contents: write
  
jobs:
  append-temp-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Append temp files to main files
      run: |
        for i in {1..8}; do
          temp_file="hall_effect_sensor_${i}_temp.txt"
          main_file="hall_effect_sensor_${i}.txt"
          if [ -f "$temp_file" ]; then
            cat "$temp_file" >> "$main_file"
            echo "Appended $temp_file to $main_file"
          else
            echo "$temp_file does not exist"
          fi
        done

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Append temp files to main files"
        git push
