name: Append Temp Files

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  append-temp-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Append temp files to main files
      continue-on-error: true
      run: |
        set -e
        trap 'echo "Error: Process completed with exit code 1"; exit 1' ERR
        for i in {1..8}; do
          temp_file="hall_effect_sensor_${i}_temp.txt"
          main_file="hall_effect_sensor_${i}.txt"
          if [ -f "$temp_file" ]; then
            last_line_main=$(tail -n 1 "$main_file")
            first_line_temp=$(head -n 1 "$temp_file")
            if [ "$last_line_main" != "$first_line_temp" ]; then
              cat "$temp_file" >> "$main_file"
              echo "Appended $temp_file to $main_file"
            else
              echo "No changes: last line of $main_file is the same as the first line of $temp_file"
            fi
          else
            echo "$temp_file does not exist"
          fi
        done

    - name: Commit changes
      continue-on-error: true
      run: |
        set -e
        trap 'echo "Error: Process completed with exit code 1"; exit 1' ERR
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Append temp files to main files"
        git push
