name: Calculate SHA of Files

on:
  push:
    branches:
      - main


permissions:  
  contents: write

jobs:
  calculate_sha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow  # Install Pillow for image processing, if needed

      - name: Calculate SHA for Files
        run: |
          import hashlib
          import json
          import os

          # Specify the files for which you want to calculate SHA
          files_to_hash = [
              'hall_effect_sensor_1.txt',
              'hall_effect_sensor_2.txt',
              'hall_effect_sensor_3.txt',
              'hall_effect_sensor_4.txt',
              'hall_effect_sensor_5.txt',
              'hall_effect_sensor_6.txt',
              'hall_effect_sensor_7.txt',
              'hall_effect_sensor_8.txt',
          ]

          sha_mapping = {}

          for file in files_to_hash:
              if os.path.exists(file):
                  with open(file, 'rb') as f:
                      file_hash = hashlib.sha1()  # You can use sha256() if needed
                      while chunk := f.read(8192):
                          file_hash.update(chunk)
                  sha_mapping[file] = file_hash.hexdigest()

          # Write the SHA mapping to a JSON file
          with open('sha_dump.json', 'w') as json_file:
              json.dump(sha_mapping, json_file, indent=4)

      - name: Commit SHA JSON
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add sha_dump.json
          git commit -m "Update SHA dump"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
