name: Calculate File SHAs

on:
  push:
    branches:
      - main  # Adjust this to your default branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  calculate-shas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calculate SHAs
        run: |
          # Create or clear the output file
          echo "" > sha_dump.txt
          
          # Loop through the specified files and calculate SHAs
          for i in {1..8}; do
            file="hall_effect_sensor_${i}.txt"
            if [ -f "$file" ]; then  # Check if the file exists
              sha=$(git rev-parse HEAD:$file)
              echo "SHA for $file: $sha" >> sha_dump.txt
            else
              echo "$file does not exist." >> sha_dump.txt
            fi
          done

          # Display the contents of the sha_dump.txt file
          cat sha_dump.txt

      - name: Commit SHA Dump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sha_dump.txt
          git commit -m "Update sha_dump.txt with file SHAs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token to push changes
